#!/usr/bin/env node
// SPDX-License-Identifier: AGPL-3.0-only
// Pull each fx-Telarana contract's ABI out of forge build artifacts and emit a
// minimal TypeScript module per contract under src/abis/. Re-run after any
// contract change.

import { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const ROOT = resolve(__dirname, "../../..");
const OUT = resolve(ROOT, "contracts/out");
const TARGET = resolve(__dirname, "../src/abis");

const CONTRACTS = [
  ["FxOracle", "FxOracle"],
  ["FxMarketRegistry", "FxMarketRegistry"],
  ["FxReceipt", "FxReceipt"],
  ["FxLiquidator", "FxLiquidator"],
  ["FxHubMessageReceiver", "FxHubMessageReceiver"],
  ["FxHyperlaneHubReceiver", "FxHyperlaneHubReceiver"],
  ["TelaranaGatewayHubHook", "TelaranaGatewayHubHook"],
  ["FxGhostCommitmentRegistry", "FxGhostCommitmentRegistry"],
  ["FxGhostSpokeRouter", "FxGhostSpokeRouter"],
  ["FxGhostKycHook", "FxGhostKycHook"],
  ["FxSpoke", "FxSpoke"],
  ["FxSpokeIntentRouter", "FxSpokeIntentRouter"],
  ["FxSwapHook", "FxSwapHook"],
  ["MorphoOracleAdapter", "MorphoOracleAdapter"],
  ["IFxOracle", "IFxOracle"],
  ["IFxMarketRegistry", "IFxMarketRegistry"],
  ["IFxSpoke", "IFxSpoke"],
  ["IFxHubMessageReceiver", "IFxHubMessageReceiver"],
  ["IBufiKycPass", "IBufiKycPass"],
];

const MANUAL_EXPORTS = [
  `export { HyperlaneWarpRouteAbi } from "./HyperlaneWarpRoute.js";`,
  `export { HyperlaneInterchainAccountRouterAbi } from "./HyperlaneInterchainAccountRouter.js";`,
];

function findArtifactPath(solFile, contractName) {
  const artifactDir = resolve(OUT, `${solFile}.sol`);
  const exact = resolve(artifactDir, `${contractName}.json`);
  if (existsSync(exact)) return exact;

  if (!existsSync(artifactDir)) return null;
  const candidates = readdirSync(artifactDir)
    .filter((file) => file.startsWith(`${contractName}.`) && file.endsWith(".json"))
    .sort();
  if (candidates.length === 0) return null;
  return resolve(artifactDir, candidates[candidates.length - 1]);
}

mkdirSync(TARGET, { recursive: true });

const artifacts = [];
for (const [solFile, contractName] of CONTRACTS) {
  const artifactPath = findArtifactPath(solFile, contractName);
  if (!artifactPath) {
    throw new Error(
      `missing artifact for ${solFile}.sol/${contractName}. Run a full forge build before syncing ABIs.`,
    );
  }
  const artifact = JSON.parse(readFileSync(artifactPath, "utf8"));
  artifacts.push([contractName, artifact.abi]);
}

const indexLines = [];
for (const [contractName, abi] of artifacts) {
  const ts = `// SPDX-License-Identifier: Apache-2.0\n// AUTO-GENERATED by scripts/sync-abis.mjs — do not edit.\nexport const ${contractName}Abi = ${JSON.stringify(
    abi,
    null,
    2
  )} as const;\n`;
  writeFileSync(resolve(TARGET, `${contractName}.ts`), ts);
  indexLines.push(`export { ${contractName}Abi } from "./${contractName}.js";`);
  console.log(`wrote src/abis/${contractName}.ts`);
}

writeFileSync(
  resolve(TARGET, "index.ts"),
  `// SPDX-License-Identifier: Apache-2.0\n${indexLines.concat(MANUAL_EXPORTS).join("\n")}\n`,
);
console.log(`wrote src/abis/index.ts with ${indexLines.length + MANUAL_EXPORTS.length} exports`);
