#!/usr/bin/env node
// Pull each fx-Telarana contract's ABI out of forge build artifacts and emit a
// minimal TypeScript module per contract under src/abis/. Re-run after any
// contract change.

import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const ROOT = resolve(__dirname, "../../..");
const OUT = resolve(ROOT, "contracts/out");
const TARGET = resolve(__dirname, "../src/abis");

const CONTRACTS = [
  ["FxOracle", "FxOracle"],
  ["FxMarketRegistry", "FxMarketRegistry"],
  ["FxReceipt", "FxReceipt"],
  ["FxLiquidator", "FxLiquidator"],
  ["FxHubMessageReceiver", "FxHubMessageReceiver"],
  ["FxSpoke", "FxSpoke"],
  ["FxSwapHook", "FxSwapHook"],
  ["MorphoOracleAdapter", "MorphoOracleAdapter"],
  ["IFxOracle", "IFxOracle"],
  ["IFxMarketRegistry", "IFxMarketRegistry"],
  ["IFxSpoke", "IFxSpoke"],
  ["IFxHubMessageReceiver", "IFxHubMessageReceiver"],
];

mkdirSync(TARGET, { recursive: true });

const indexLines = [];
for (const [solFile, contractName] of CONTRACTS) {
  const artifactPath = resolve(OUT, `${solFile}.sol/${contractName}.json`);
  if (!existsSync(artifactPath)) {
    console.warn(`skip: missing artifact ${artifactPath}`);
    continue;
  }
  const artifact = JSON.parse(readFileSync(artifactPath, "utf8"));
  const abi = artifact.abi;
  const ts = `// AUTO-GENERATED by scripts/sync-abis.mjs — do not edit.\nexport const ${contractName}Abi = ${JSON.stringify(
    abi,
    null,
    2
  )} as const;\n`;
  writeFileSync(resolve(TARGET, `${contractName}.ts`), ts);
  indexLines.push(`export { ${contractName}Abi } from "./${contractName}.js";`);
  console.log(`wrote src/abis/${contractName}.ts`);
}

writeFileSync(resolve(TARGET, "index.ts"), indexLines.join("\n") + "\n");
console.log(`wrote src/abis/index.ts with ${indexLines.length} exports`);
