// AUTO-GENERATED by scripts/sync-abis.mjs — do not edit.
export const IFxOracleAbi = [
  {
    "type": "function",
    "name": "config",
    "inputs": [],
    "outputs": [
      {
        "name": "maxOracleAge",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "maxDeviationBps",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "maxConfidenceBps",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getMid",
    "inputs": [
      {
        "name": "base",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "quote",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "midE18",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "publishedAt",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getMidVerified",
    "inputs": [
      {
        "name": "base",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "quote",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "midE18",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "publishedAt",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getMidWithUpdate",
    "inputs": [
      {
        "name": "base",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "quote",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "pythUpdate",
        "type": "bytes[]",
        "internalType": "bytes[]"
      }
    ],
    "outputs": [
      {
        "name": "midE18",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "publishedAt",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "payable"
  },
  {
    "type": "error",
    "name": "OracleDeviation",
    "inputs": [
      {
        "name": "primaryE18",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "secondaryE18",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "bpsObserved",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "bpsMax",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "OracleFeedUnknown",
    "inputs": [
      {
        "name": "base",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "quote",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "OracleLowConfidence",
    "inputs": [
      {
        "name": "confBps",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "maxConfBps",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "OracleStale",
    "inputs": [
      {
        "name": "publishedAt",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "maxAge",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "RedstoneFeedUnknown",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      }
    ]
  }
] as const;
